server:
  port: 7090

spring:
  application:
    name: trade-cloud-gateway-service

  cloud:
    gateway:
      routes:
        - id: trade-auth-service
          uri: http://localhost:3040
          predicates:
            - Path=/auth/**

        - id: trade-broker-service
          uri: http://localhost:3077
          predicates:
            - Path=/broker/**

        - id: trade-user-service
          uri: http://localhost:3066
          predicates:
            - Path=/users/**


        - id: trade-market-service
          uri: http://localhost:3022
          predicates:
            - Path=/market/**            


        - id: trade-strategy-service
          uri: http://localhost:3011
          predicates:
            - Path=/strategy/**            


auth:
  service:
    url: http://localhost:3040             

jwt:
  secret: 9Jt1c7zP6QwV8Lr5xC6vK0Z4E2m7R8H9nFJ3S5aQ2Wk=
